#!/usr/bin/env node

import { program } from 'commander';
import fsSync from 'node:fs';
import { join } from 'node:path';
import supabaseToZod, { supabaseToZodOptionsSchema } from './supabase-to-zod';
import * as url from 'url';

const __dirname = url.fileURLToPath(new URL('.', import.meta.url));
const defaultPackageJsonPath = join(__dirname, 'package.json');
const packageJsonPath = fsSync.existsSync(defaultPackageJsonPath)
  ? defaultPackageJsonPath
  : join(__dirname, '../package.json');

const packageJson = JSON.parse(
  fsSync.readFileSync(packageJsonPath, {}).toString(),
);

program
  .name(packageJson.name)
  .version(packageJson.version)
  .option('-i, --input <input>', 'Path to the types generated by supabase cli')
  .option('-o, --output <output>', 'Path to the output file')
  .option('-s, --schema [schema]', 'Specify schema', 'public')
  .option(
    '-sr, --relationships',
    'Output relationship schemas found in the supabase schema',
  )
  .option(
    '-su, --updates',
    'Output update schemas found in the supabase schema',
  )
  .option(
    '-si, --inserts',
    'Output insert schemas found in the supabase schema (default)',
  )
  .option(
    '-sd, --deletes',
    'Output delete schemas found in the supabase schema',
  )
  .parse(process.argv);
const opts = supabaseToZodOptionsSchema.parse(program.opts());
void (async () => {
  try {
    await supabaseToZod(opts);
    process.exit();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
})();
